### ISSUE TITLE
Enhancement Request: UK Holidays

### ISSUE THREAD

**Issue by pich** [umulmrum/holiday#15]
While utilizing this library, I realised that support for tracking UK holidays is missing. To better cater to UK-based users, I propose the implementation of this feature in a future update.

btw: This [PR](https://github.com/umulmrum/holiday/pull/14) potentially closes my issue.

**Comment by umulmrum** [comment]
Thanks for your input and sorry for the long delay. An implementation for UK will be available in release 0.7 shortly.
