### ISSUE TITLE
Invalid location alias: SUNDAYS when using HolidayHelper::getNoWorkDaysForTimespan()

### ISSUE THREAD

**Issue by spackmat** [umulmrum/holiday#2]
Hi, nice library! On my first usage attempt, I get an error message, when I use `HolidayHelper::getNoWorkDaysForTimespan()`:

    $holidayCalculator = new HolidayCalculator(new GermanyHolidayInitializer())
    $holidayHelper = new HolidayHelper($holidayCalculator);
    $holidays = $holidayHelper->getNoWorkDaysForTimespan(
        new \DateTime('2018-10-01'),
        new \DateTime('2018-10-31'),
        'DE-NW'
    );

This throws a HolidayException: "Invalid location alias: SUNDAYS".

The problem is, that I have to add (at least) Sundays as an HolidayProvider:

    $holidayCalculator->addHolidayProvider(new Sundays());

This is a bit confusing. I expected the `getNoWorkDaysForTimespan()` method to add the provided `$noWorkWeekdayProviders` automatically using `$holidayCalculator->addHolidayProvider();`, if they are not added yet. This is already done in `$temporaryHolidayCalculator`, but the line calculating sundays doesn't make use of use it.

Is this a bug?

Greets, spackmat :)

**Comment by umulmrum** [comment]
Hi :-)

Thanks for noticing - this is a bug in any case, as it doesn't make sense to call the calculator fixed to Sundays. I built a fix in branch fix/2-noworkdays-helper  - could you do a quick check if this fixes your problem?

**Comment by spackmat** [comment]
Sorry for my late answer. Your fix works in my case. :)

**Comment by umulmrum** [comment]
Good - I merged it and release version 0.2.1. Thanks for your help.
