### ISSUE TITLE
"Corpus christi" (May 30 2024) is listed as "HolidayType Other" for Hesse, Germany

### ISSUE THREAD

**Issue by NicoHaase** [umulmrum/holiday#43]
In https://github.com/umulmrum/holiday/blob/master/src/Provider/Germany/Hesse.php, "Corpus christi" is not listed as a proper "day off" for Hesse, which looks like a bug to me. Do you remember why it is listed as "Other" in Hesse, but not in the other states of Germany?

https://www.rv.hessenrecht.hessen.de/bshe/document/jlr-FeiertGHE1952rahmen is the official list of holidays provided by the state, and it lists the days in https://www.rv.hessenrecht.hessen.de/bshe/document/jlr-FeiertGHE1952pP1, where "Himmelfahrtstag" (the german name) is officially listed.

**Comment by umulmrum** [comment]
Hi @NicoHaase, to be honest, I have no idea and this must be a mistake. I'll change it to DAY_OFF instead (I'm about to release 0.10.0 anyway so this is perfect timing). Thanks for the report!

(just to be the overly correct guy: Corpus Christi is Fronleichnam in German, Ascension is Himmelfahrt :slightly_smiling_face:)

**Comment by umulmrum** [comment]
Fixed in 0.10.0 :slightly_smiling_face:

**Comment by NicoHaase** [comment]
Thanks for the quick help - and maybe I'll keep these holidays sorted now :D
