### ISSUE TITLE
AbstractSortFilter uses wrong namespacing

### ISSUE THREAD

**Issue by NicoHaase** [umulmrum/holiday#9]
https://github.com/umulmrum/holiday/blob/master/src/Filter/AbstractSortFilter.php#L12 should not contain a lower-cased namespacing. This causes problems in Symfony, as their ClassLoader checks for such cases in https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/ErrorHandler/DebugClassLoader.php#L380

**Comment by umulmrum** [comment]
Just released version 0.5.1 which should solve this - thanks for reporting :-)

**Comment by NicoHaase** [comment]
Thanks for the quick reply, everything works fine now :)
